version: '3.5'

# For this configuration to work properly, you must have a license file mounted into the dotcms service.
# Without a license file, the external ES service will NOT be recognized and utilized.  All documents will
# indexed on the dotcms node directly and will not be persisted between restarts.

networks:
  http_net:
  db_net:
  es_net:

volumes:
  cms-shared:
  #cms-local:
  dbdata:
  esdata:
  
secrets:
   connection.pool.name:
    external: true
    name: connection.pool.name
   connection.db.base.url:
    external: true
    name: connection.db.base.url
   connection.db.driver:
    external: true
    name: connection.db.driver
   connection.db.leak.detection.threshold:
    external: true
    name: connection.db.leak.detection.threshold
   connection.db.max.idle:
    external: true
    name: connection.db.max.idle
   connection.db.max.total:
    external: true
    name: connection.db.max.total
   connection.db.max.wait:
    external: true
    name: connection.db.max.wait
   connection.db.name:
    external: true
    name: connection.db.name
   connection.db.password:
    external: true
    name: connection.db.password
   connection.db.username:
    external: true
    name: connection.db.username
   connection.db.validation.query:
    external: true
    name: connection.db.validation.query
    ##Uncomment these lines in case you need to define a default transaction isolation 
   #connection.db.default.transaction.isolation:
   # external: true
   # name: connection.db.default.transaction.isolation

services:
  http:
    image: dotcms/haproxy:1.8-os
    environment:
      "HAPROXY_CERT_PATH": '/certs/'
#      "HAPROXY_REDIRECT_HTTPS_ALL": 'true'
#      "HAPROXY_MAINTENANCE_PAGE": '/srv/config/503.http'

    ports:
      - "80:8080"
      - "443:8443"
#    volumes:
#      - /data/dotcms/haproxy/certs:/certs:ro
#      - /data/dotcms/haproxy/503.http:/srv/config/503.http:ro

    networks:
      - http_net

  elasticsearch:
    image: gcr.io/cicd-246518/es-open-distro:1.2.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1500m'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX": '2'
      "ES_ADMIN_PASSWORD": 'admin'
      discovery.type: single-node
    volumes:
      - esdata:/data
    networks:
      - es_net

  dotcms:
    image: dotcms/dotcms:latest
    environment:
      "CMS_HEAP_SIZE": '2g'
      "CMS_JAVA_OPTS": '-XX:+PrintFlagsFinal'
      "PROVIDER_DB_DNSNAME": 'db'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch'
      "ES_ADMIN_PASSWORD": 'admin'
    depends_on:
      - elasticsearch
      - db
      - http
    volumes:
      - cms-shared:/data/shared
      #- [serverpath]/license.dat:/data/local/dotsecure/license/license.dat
      #- [serverpath]/license.zip:/data/shared/assets/license.zip
    networks:
      - db_net
      - http_net
      - es_net
    secrets:
      - connection.db.base.url
      - connection.db.driver
      - connection.db.leak.detection.threshold
      - connection.db.max.idle
      - connection.db.max.total
      - connection.db.max.wait
      - connection.pool.name
      - connection.db.password
      - connection.db.username
      - connection.db.validation.query

  db:
    image: postgres:11
    ports:
      - "15432:5432"
    environment: 
        "POSTGRES_PASSWORD_FILE": /run/secrets/connection.db.password
        "POSTGRES_USER_FILE": /run/secrets/connection.db.username
        "POSTGRES_DB_FILE": /run/secrets/connection.db.name
    secrets:
      - connection.db.name
      - connection.db.password
      - connection.db.username
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db_net
