apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dotcmsassets-pvc
  spec:
    accessModes:
    - ReadWriteMany
    storageClassName: ""
    resources:
      requests:
        storage: 5Gi
    volumeName: dotcmsassets
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dbdata-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: ""
    resources:
      requests:
        storage: 10Gi
    volumeName: dbdata
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: es-static-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: ""
    resources:
      requests:
        storage: 10Gi
    volumeName: es-static
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dotcmsplugins-pvc
  spec:
    accessModes:
    - ReadWriteMany
    storageClassName: ""
    resources:
      requests:
        storage: 500Mi
    volumeName: dotcmsplugins
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: dbdata-pvc
        containers:
        - name: postgres
          image: bitnami/postgresql:9.6
          imagePullPolicy: Always
          ports:
          - containerPort: 5432
            protocol: TCP
          env:
          - name: POSTGRESQL_USERNAME
            value: dotcmsdbuser
          - name: POSTGRESQL_PASSWORD
            value: password
          - name: POSTGRESQL_DATABASE
            value: dotcms   
          volumeMounts:
          - name: dbdata
            mountPath: /bitnami/postgresql
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    name: db-svc
  spec:
    ports:
    - port: 5432
    selector:
      app: postgres
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: elasticsearch-static
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: elasticsearch-static
        apptype: elasticsearch
        appversion: 6.1.3
    template:
      metadata:
        labels:
          app: elasticsearch-static
          apptype: elasticsearch
          appversion: 6.1.3
      spec:
        volumes:
        - name: esstaticstorage
          persistentVolumeClaim:
            claimName: es-static-pvc
        containers:
        - name: esstatic
          image: dotcms/elasticsearch:6.1.3-os
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 9200
            protocol: TCP
          - name: transport
            containerPort: 9300
            protocol: TCP
          env:
          - name: PROVIDER_ELASTICSEARCH_HEAP_SIZE
            value: 1500m
          - name: PROVIDER_ELASTICSEARCH_DNSNAMES
            value: elasticsearch-svc
          - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN
            value: "1"
          - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP
            value: "1"
          - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
            value: "2"
          - name: PROVIDER_ELASTICSEARCH_ADDR_TRANSPORT
            value: "0.0.0.0"
          volumeMounts:
          - name: esstaticstorage
            mountPath: /data
        restartPolicy: Always
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: elasticsearch
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: elasticsearch
        apptype: elasticsearch
        appversion: 6.1.3
    template:
      metadata:
        labels:
          app: elasticsearch
          apptype: elasticsearch
          appversion: 6.1.3
      spec:
        containers:
        - name: es
          image: dotcms/elasticsearch:6.1.3-os
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 9200
            protocol: TCP
          - name: transport
            containerPort: 9300
            protocol: TCP
          env:
          - name: PROVIDER_ELASTICSEARCH_HEAP_SIZE
            value: 1500m
          - name: PROVIDER_ELASTICSEARCH_DNSNAMES
            value: elasticsearch-svc
          - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN
            value: "5"
          - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP
            value: "1"
          - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
            value: "15"
          - name: PROVIDER_ELASTICSEARCH_ADDR_TRANSPORT
            value: "0.0.0.0"
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
      name: elasticsearch-svc
  spec:
    ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
    selector:
      apptype: elasticsearch
      appversion: 6.1.3
    type: ClusterIP
    clusterIP: None
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hazelcast
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hazelcast
        apptype: hazelcast
        appversion: 3.9.2
    template:
      metadata:
        labels:
          app: hazelcast
          apptype: hazelcast
          appversion: 3.9.2
      spec:
        containers:
        - name: hazelcast
          image: dotcms/hazelcast:3.9.2-os
          imagePullPolicy: Always
          env:
          - name: PROVIDER_HAZELCAST_DNSNAMES
            value: hazelcast-svc
          - name: PROVIDER_HAZELCAST_HEAP_MIN
            value: 128m
          - name: PROVIDER_HAZELCAST_HEAP_MAX
            value: 512m
          - name: PROVIDER_HAZELCAST_MANCENTER_ENABLED
            value: "true"
          - name: PROVIDER_HAZELCAST_MANCENTER_URL
            value: "http://hazelcast-mancenter-svc:8080/mancenter"
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
      name: hazelcast-svc
  spec:
    ports:
    - name: http
      port: 5701
    selector:
      apptype: hazelcast
      appversion: 3.9.2
    type: ClusterIP
    clusterIP: None
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hazelcast-mancenter
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hazelcast-mancenter
        apptype: hazelcast-mancenter
        appversion: 3.9.2
    template:
      metadata:
        labels:
          app: hazelcast-mancenter
          apptype: hazelcast-mancenter
          appversion: 3.9.2
      spec:
        containers:
        - name: hazelcast-mancenter
          image: dotcms/hazelcast-mancenter:3.9.2-os
          imagePullPolicy: Always
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    name: hazelcast-mancenter-svc
  spec:
    selector:
      apptype: hazelcast-mancenter
      appversion: 3.9.2
    ports:
    - name: http
      port: 8080
    type: LoadBalancer
    sessionAffinity: ClientIP            
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: dotcms
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: dotcms
    template:
      metadata:
        labels:
          app: dotcms
      spec:
        volumes:
        - name: assetsvolume
          persistentVolumeClaim:
            claimName: dotcmsassets-pvc
        - name: licensefile
          configMap:
            name: dotcmslicensepack
        - name: plugins
          persistentVolumeClaim:
            claimName: dotcmsplugins-pvc
        containers:
        - name: dotcms
          image: dotcms/dotcms:5.1.6-os
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
          - name: CMS_HEAP_SIZE
            value: 2G
          - name: CMS_JAVA_OPTS
            value: -XX:+PrintFlagsFinal
          - name: PROVIDER_DB_DNSNAME
            value: db-svc
          - name: PROVIDER_ELASTICSEARCH_DNSNAMES
            value: elasticsearch-svc
          - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
            value: "60"            
          - name: PROVIDER_HAZELCAST_DNSNAMES
            value: hazelcast-svc 
          - name: PROVIDER_LOADBALANCER_DNSNAMES
            value: haproxy-svc 
          - name: PROVIDER_LOADBALANCER_PORT_HTTP
            value: "80"               
          volumeMounts:
          - name: assetsvolume
            mountPath: /data/shared/assets
          - name: licensefile
            mountPath: /data/shared/assets/license.zip
            subPath: "license.zip"
          - name: plugins
            mountPath: /plugins
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    name: dotcms
  spec:
    ports:
    - name: dotcms
      port: 8081
      protocol: TCP
    selector:
      app: dotcms
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: haproxy
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: haproxy 
    template:
      metadata:
        name: haproxy
        labels:
          app: haproxy
      spec:
        containers:
        - name: haproxy
          image: dotcms/haproxy:1.8-os
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
- apiVersion: v1
  kind: Service
  metadata:
    name: haproxy-svc
  spec:
    selector:
      app: haproxy
    ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
    type: LoadBalancer
    sessionAffinity: ClientIP        

